### ISSUE TITLE
Connection to bike

### ISSUE THREAD

**Issue by mileseverett** [pocable/BowflexC6#1]
Hello

How are you connecting to the bike? I have been trying for days with the Scwinn IC8 but bluetooth pairing is failing, this is the European branding for your bike so I assume it would be the same software too? 

Thanks
Miles

**Comment by pocable** [comment]
I am not sure with the Scwinn bikes but it could potentially be the same software. What I did to connect was use the [Serial Bluetooth Terminal](https://play.google.com/store/apps/details?id=de.kai_morich.serial_bluetooth_terminal&hl=en_CA&gl=US). Make sure you pedal to turn on the display and then it should pop up as IC Bike (could be different for Scwinn) when you scan for bluetooth devices in the app. Make sure for the Bluetooth LE Profile you pick custom and select the right Service, Read and Write UUIDs or it will not connect.

**Comment by mileseverett** [comment]
Yeah it pops up as IC bike, any chance you could show an example of the Bluetooth LE Profile? I connect and it times out during pairing. Feel free to black out the mac address!

**Comment by pocable** [comment]
![Screenshot_20210211-142703_Serial Bluetooth Terminal~2](https://user-images.githubusercontent.com/2263546/107700906-62d48380-6c75-11eb-9f36-71da19833bef.jpg)
![Screenshot_20210211-142644_Serial Bluetooth Terminal](https://user-images.githubusercontent.com/2263546/107700930-69fb9180-6c75-11eb-8e4c-a61059dc9170.jpg)
Here is what mine looks like. Tap on IC bike to get to the second screen.

**Comment by mileseverett** [comment]
Greatly appreciated, thanks!
